object SymptomRegions {

    const val HEAD = "Head"
    const val FOREHEAD = "Forehead"
    const val TEMPORAL = "Temporal region"
    const val OCCIPITAL = "Occipital region"
    const val FACE = "Face"
    const val EYE = "Eye"
    const val EAR = "Ear"
    const val NOSE = "Nose"
    const val MOUTH = "Mouth"
    const val THROAT = "Throat"

    const val NECK = "Neck"
    const val ANTERIOR_NECK = "Anterior neck"
    const val POSTERIOR_NECK = "Posterior neck"

    const val CHEST = "Chest"
    const val LEFT_CHEST = "Left chest"
    const val RIGHT_CHEST = "Right chest"
    const val CENTRAL_CHEST = "Central chest"
    const val RIBS = "Ribs"
    const val STERNUM = "Sternum"

    const val BACK = "Back"
    const val UPPER_BACK = "Upper back"
    const val MID_BACK = "Mid back"
    const val LOWER_BACK = "Lower back"
    const val LUMBAR = "Lumbar region"
    const val SACRAL = "Sacral region"

    const val ABDOMEN = "Abdomen"
    const val EPIGASTRIC = "Epigastric region"
    const val UMBILICAL = "Umbilical region"
    const val LEFT_UPPER_ABDOMEN = "Left upper abdomen"
    const val RIGHT_UPPER_ABDOMEN = "Right upper abdomen"
    const val LEFT_LOWER_ABDOMEN = "Left lower abdomen"
    const val RIGHT_LOWER_ABDOMEN = "Right lower abdomen"

    const val PELVIS = "Pelvis"
    const val GROIN = "Groin"
    const val GENITAL = "Genital region"
    const val PERINEUM = "Perineum"

    const val SHOULDER = "Shoulder"
    const val ARM = "Arm"
    const val ELBOW = "Elbow"
    const val FOREARM = "Forearm"
    const val WRIST = "Wrist"
    const val HAND = "Hand"
    const val FINGERS = "Fingers"

    const val HIP = "Hip"
    const val THIGH = "Thigh"
    const val KNEE = "Knee"
    const val LEG = "Leg"
    const val ANKLE = "Ankle"
    const val FOOT = "Foot"
    const val TOES = "Toes"

    const val GENERALIZED = "Generalized"
    const val SCALP = "Scalp"
const val ORBIT = "Orbit"
const val MAXILLA = "Maxilla"
const val MANDIBLE = "Mandible"
const val CLAVICLE = "Clavicle"
const val SCAPULA = "Scapula"
const val BUTTOCK = "Buttock"
const val PERIANAL = "Perianal"
const val AXILLA = "Axilla"

}